### ISSUE TITLE
Make `link:` work

### ISSUE THREAD

**Issue by brillout** [snake-py/eject#7]
At https://github.com/snake-py/eject/pull/6 I replaced `file:` with `link:` because `file:` doesn't properly work.

> [!NOTE]
> The issue with `file:` is that it uses [hard links instead of symlinks](https://pnpm.io/cli/link#whats-the-difference-between-pnpm-link-and-using-the-file-protocol). And, [consequently](https://askubuntu.com/questions/210741/why-are-hard-links-not-allowed-for-directories), the directly `ejected/some-library/` isn't actually symlinked (only its files are hard-linked).

Using `link:` instead of `file:` works (and I expect it to work reliably since it's a ubiquitous technique). The only issue is that the dependencies of `ejected/some-library/` aren't automatically installed. A solution would be to add `ejected/some-library/` to `pnpm-workspace.yaml` (or create one if it doesn't exist). Same for npm and Yarn.

**Comment by brillout** [comment]
Eject now also works with `vike-react`, starting with `vike@0.4.202`.

Demo using `link:` while adding `ejected/vike-react/` to `pnpm-workspace.yaml`:  https://github.com/vikejs/vike/commit/5e2793907225456ee2c095d6ee646714c737ae61.

Once this and  https://github.com/snake-py/eject/issues/2 is implemented, I'll start mentioning the `eject` package to Vike's docs :rocket:

**Comment by snake-py** [comment]
I'll take care of this over the weekend. Have a lot of different stuff to do right now.

**Comment by brillout** [comment]
See the note [here](https://github.com/snake-py/eject/issues/7#issue-2662245853). Try to add a file `touch ejected/some-lib/new-file` and you'll see that it will be missing in `node_modules/some-lib/`. That's because file inside the directory is hard linked, instead of the directory itself being soft linked.

**Comment by snake-py** [comment]
> Using link: instead of file: works

Really I get:

```
✅ Ejected dependencies: express
📦 Running npm install to update package-lock.json
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "link:": link:./ejected/express
npm error A complete log of this run can be found in: /home/fabio/.npm/_logs/2024-11-27T14_38_24_097Z-debug-0.log
node:internal/errors:865
  const err = new Error(message);
              ^

Error: Command failed: npm install
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at CAC.eject (file:///home/fabio/Desktop/playground/eject/dist/esm/command.js:40:5)
    at CAC.runMatchedCommand (file:///home/fabio/Desktop/playground/eject/node_modules/cac/dist/index.mjs:610:34)
    at CAC.parse (file:///home/fabio/Desktop/playground/eject/node_modules/cac/dist/index.mjs:537:12)
    at file:///home/fabio/Desktop/playground/eject/dist/esm/index.js:13:5
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadESM (node:internal/process/esm_loader:34:7) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 35827,
  stdout: null,
  stderr: null
}

Node.js v18.19.0
```

**Comment by snake-py** [comment]
Okay wait then let me understand the issue with file first. Maybe it makes sense to do one or the other for different dependency managers.

**Comment by snake-py** [comment]
So first of all support:

## npm 

[Doc](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#dependencies)

They only have `file` protocol.

## pnpm

Support either, see [doc](https://pnpm.io/cli/link#whats-the-difference-between-pnpm-link-and-using-the-file-protocol).

## yarn

Also only supports `file` - see [docs](https://classic.yarnpkg.com/lang/en/docs/cli/add/#toc-adding-dependencies).

## bun

Not sure I think they [want to support](https://github.com/oven-sh/bun/issues/5045) `link` but currently cannot.

**Comment by snake-py** [comment]
SO the issue, you have with `file` is really a monorepo issue. You want that the ejected dependency links back to `node_modules`? 

I would claim that this is not the most common case, shall we maybe simply have a flag `--link` which would then use the `link` protocol and then write in the docs that this needs to be done? I also think you can manually change back from `file` to link in case you want that. If you are a maintainer of a monorepo you should know how to deal with that? Let me know what you think.

**Comment by brillout** [comment]
Using `file:` doesn't work at all with pnpm, regardless of whether the user has a monorepo or not. The issue being what I described [here](https://github.com/snake-py/eject/issues/7#issuecomment-2503910512). Imagine you start modifying `ejected/some-lib` and, in the process, you create a new file `ejected/some-lib/some-new-file`. That new file will be missing: `node_modules/some-lib/some-new-file` doesn't exist. That essentially breaks everything.

You can try doing some refactoring after you eject, you'll see the problem. (For example just rename a file.)

Maybe it's just a `pnpm` issue?

**Comment by brillout** [comment]
> You want that the ejected dependency links back to `node_modules`?

That's unrelated to pnpm and unrelated to monorepos. It needs to be linked as `node_modules/some-lib` so that `import { something } from 'some-lib'` works.

**Comment by snake-py** [comment]
@brillout for me `file` works if I do simply:

1. `pnpm create vite`
2. `pnpm i`
3. `npx eject react`
4. `pnpm run dev`

Am I doing something wrong? I am leaning towards adding `link` as flag. Maybe I am not understanding something fully.

**Comment by brillout** [comment]
Rename any file inside `ejected/react/` (and update all imports). You'll see it will break. Explanation: https://github.com/snake-py/eject/issues/7#issuecomment-2504096672.

**Comment by snake-py** [comment]
@brillout a general question about pnpm, since I don't know it too much. If we eject using `pnpm`, and then alter the code in a project, won't we alter the library for all other project on our machine? If this is the case I think we should mark the library using a new name so that the ejected library and the original library can be used.

**Comment by brillout** [comment]
No it doesn't; that's actually why we replace the package version with `link:`.

**Comment by snake-py** [comment]
I guess with this resolved we can consider to make a new release.

**Comment by snake-py** [comment]
Pushed new tag 1.0.2
