### ISSUE TITLE
Add an E2E automated test pipeline

### ISSUE THREAD

**Issue by snake-py** [snake-py/eject#9]
I think we can simply have a pipeline in which we are creating a new project and then use eject command and check if everything was ejected like expected.

Basically:

1. checkout current code
2. build 
3. link
4. cd to empty folder
5. clone eject-test-repo (which is a simple app using npm)
7. npm run build
8. eject dependency
9. have script assert the ejected results

**Comment by brillout** [comment]
Sounds good. (Although IMHO I feel like it's low prio for now.)

**Comment by snake-py** [comment]
@brillout I'll do it, because it is a pain to test it manually all the time.

**Comment by brillout** [comment]
:+1:
